version: '2'

services:
  node-webpack:
    build:
      dockerfile: ./Dockerfile
      context: .

    ports:
      - "8080:8080"

    volumes:
      - ./:/code/
      - /code/node_modules

    command: npm run dev
